services:
  auth-service:
    extra_hosts:
      - "host.docker.internal:host-gateway"

  parkinglot-service:
    extra_hosts:
      - "host.docker.internal:host-gateway"

  parkingspot-service:
    extra_hosts:
      - "host.docker.internal:host-gateway"

  vehicle-service:
    extra_hosts:
      - "host.docker.internal:host-gateway"

  booking-service:
    extra_hosts:
      - "host.docker.internal:host-gateway"

  payment-service:
    extra_hosts:
      - "host.docker.internal:host-gateway"

  notification-service:
    extra_hosts:
      - "host.docker.internal:host-gateway"

  analytics-service:
    extra_hosts:
      - "host.docker.internal:host-gateway"