server:
  port: ${SERVER_PORT:8761}

spring:
  application:
    name: discovery-service
  boot:
    admin:
      client:
        url: ${ADMIN_SERVER_URL:http://localhost:9090}
        username: ${ADMIN_USERNAME}
        password: ${ADMIN_PASSWORD}
        instance:
          prefer-ip: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
